/**
 * @fileoverview gRPC-Web generated client stub for pingpong
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: pingpong.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.pingpong = require('./pingpong_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pingpong.PingPongServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pingpong.PingPongServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pingpong.Ping,
 *   !proto.pingpong.Pong>}
 */
const methodDescriptor_PingPongService_SendPing = new grpc.web.MethodDescriptor(
  '/pingpong.PingPongService/SendPing',
  grpc.web.MethodType.UNARY,
  proto.pingpong.Ping,
  proto.pingpong.Pong,
  /**
   * @param {!proto.pingpong.Ping} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pingpong.Pong.deserializeBinary
);


/**
 * @param {!proto.pingpong.Ping} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pingpong.Pong)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pingpong.Pong>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pingpong.PingPongServiceClient.prototype.sendPing =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pingpong.PingPongService/SendPing',
      request,
      metadata || {},
      methodDescriptor_PingPongService_SendPing,
      callback);
};


/**
 * @param {!proto.pingpong.Ping} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pingpong.Pong>}
 *     Promise that resolves to the response
 */
proto.pingpong.PingPongServicePromiseClient.prototype.sendPing =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pingpong.PingPongService/SendPing',
      request,
      metadata || {},
      methodDescriptor_PingPongService_SendPing);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pingpong.Empty,
 *   !proto.pingpong.Pong>}
 */
const methodDescriptor_PingPongService_ReceivePongStream = new grpc.web.MethodDescriptor(
  '/pingpong.PingPongService/ReceivePongStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.pingpong.Empty,
  proto.pingpong.Pong,
  /**
   * @param {!proto.pingpong.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pingpong.Pong.deserializeBinary
);


/**
 * @param {!proto.pingpong.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pingpong.Pong>}
 *     The XHR Node Readable Stream
 */
proto.pingpong.PingPongServiceClient.prototype.receivePongStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pingpong.PingPongService/ReceivePongStream',
      request,
      metadata || {},
      methodDescriptor_PingPongService_ReceivePongStream);
};


/**
 * @param {!proto.pingpong.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pingpong.Pong>}
 *     The XHR Node Readable Stream
 */
proto.pingpong.PingPongServicePromiseClient.prototype.receivePongStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pingpong.PingPongService/ReceivePongStream',
      request,
      metadata || {},
      methodDescriptor_PingPongService_ReceivePongStream);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pingpong.Ping,
 *   !proto.pingpong.Pong>}
 */
const methodDescriptor_PingPongService_PingAndStreamPong = new grpc.web.MethodDescriptor(
  '/pingpong.PingPongService/PingAndStreamPong',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.pingpong.Ping,
  proto.pingpong.Pong,
  /**
   * @param {!proto.pingpong.Ping} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pingpong.Pong.deserializeBinary
);


/**
 * @param {!proto.pingpong.Ping} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pingpong.Pong>}
 *     The XHR Node Readable Stream
 */
proto.pingpong.PingPongServiceClient.prototype.pingAndStreamPong =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pingpong.PingPongService/PingAndStreamPong',
      request,
      metadata || {},
      methodDescriptor_PingPongService_PingAndStreamPong);
};


/**
 * @param {!proto.pingpong.Ping} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.pingpong.Pong>}
 *     The XHR Node Readable Stream
 */
proto.pingpong.PingPongServicePromiseClient.prototype.pingAndStreamPong =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/pingpong.PingPongService/PingAndStreamPong',
      request,
      metadata || {},
      methodDescriptor_PingPongService_PingAndStreamPong);
};


module.exports = proto.pingpong;

