// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: pingpong.proto

package pingpong

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PingPongServiceClient is the client API for PingPongService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingPongServiceClient interface {
	SendPing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error)
	StreamPingPong(ctx context.Context, opts ...grpc.CallOption) (PingPongService_StreamPingPongClient, error)
	ReceivePongStream(ctx context.Context, in *Empty, opts ...grpc.CallOption) (PingPongService_ReceivePongStreamClient, error)
	PingAndStreamPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (PingPongService_PingAndStreamPongClient, error)
}

type pingPongServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPingPongServiceClient(cc grpc.ClientConnInterface) PingPongServiceClient {
	return &pingPongServiceClient{cc}
}

func (c *pingPongServiceClient) SendPing(ctx context.Context, in *Ping, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/pingpong.PingPongService/SendPing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingPongServiceClient) StreamPingPong(ctx context.Context, opts ...grpc.CallOption) (PingPongService_StreamPingPongClient, error) {
	stream, err := c.cc.NewStream(ctx, &PingPongService_ServiceDesc.Streams[0], "/pingpong.PingPongService/StreamPingPong", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingPongServiceStreamPingPongClient{stream}
	return x, nil
}

type PingPongService_StreamPingPongClient interface {
	Send(*Ping) error
	Recv() (*Pong, error)
	grpc.ClientStream
}

type pingPongServiceStreamPingPongClient struct {
	grpc.ClientStream
}

func (x *pingPongServiceStreamPingPongClient) Send(m *Ping) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pingPongServiceStreamPingPongClient) Recv() (*Pong, error) {
	m := new(Pong)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pingPongServiceClient) ReceivePongStream(ctx context.Context, in *Empty, opts ...grpc.CallOption) (PingPongService_ReceivePongStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &PingPongService_ServiceDesc.Streams[1], "/pingpong.PingPongService/ReceivePongStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingPongServiceReceivePongStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PingPongService_ReceivePongStreamClient interface {
	Recv() (*Pong, error)
	grpc.ClientStream
}

type pingPongServiceReceivePongStreamClient struct {
	grpc.ClientStream
}

func (x *pingPongServiceReceivePongStreamClient) Recv() (*Pong, error) {
	m := new(Pong)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pingPongServiceClient) PingAndStreamPong(ctx context.Context, in *Ping, opts ...grpc.CallOption) (PingPongService_PingAndStreamPongClient, error) {
	stream, err := c.cc.NewStream(ctx, &PingPongService_ServiceDesc.Streams[2], "/pingpong.PingPongService/PingAndStreamPong", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingPongServicePingAndStreamPongClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PingPongService_PingAndStreamPongClient interface {
	Recv() (*Pong, error)
	grpc.ClientStream
}

type pingPongServicePingAndStreamPongClient struct {
	grpc.ClientStream
}

func (x *pingPongServicePingAndStreamPongClient) Recv() (*Pong, error) {
	m := new(Pong)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PingPongServiceServer is the server API for PingPongService service.
// All implementations must embed UnimplementedPingPongServiceServer
// for forward compatibility
type PingPongServiceServer interface {
	SendPing(context.Context, *Ping) (*Pong, error)
	StreamPingPong(PingPongService_StreamPingPongServer) error
	ReceivePongStream(*Empty, PingPongService_ReceivePongStreamServer) error
	PingAndStreamPong(*Ping, PingPongService_PingAndStreamPongServer) error
	mustEmbedUnimplementedPingPongServiceServer()
}

// UnimplementedPingPongServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPingPongServiceServer struct {
}

func (UnimplementedPingPongServiceServer) SendPing(context.Context, *Ping) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPing not implemented")
}
func (UnimplementedPingPongServiceServer) StreamPingPong(PingPongService_StreamPingPongServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPingPong not implemented")
}
func (UnimplementedPingPongServiceServer) ReceivePongStream(*Empty, PingPongService_ReceivePongStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ReceivePongStream not implemented")
}
func (UnimplementedPingPongServiceServer) PingAndStreamPong(*Ping, PingPongService_PingAndStreamPongServer) error {
	return status.Errorf(codes.Unimplemented, "method PingAndStreamPong not implemented")
}
func (UnimplementedPingPongServiceServer) mustEmbedUnimplementedPingPongServiceServer() {}

// UnsafePingPongServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingPongServiceServer will
// result in compilation errors.
type UnsafePingPongServiceServer interface {
	mustEmbedUnimplementedPingPongServiceServer()
}

func RegisterPingPongServiceServer(s grpc.ServiceRegistrar, srv PingPongServiceServer) {
	s.RegisterService(&PingPongService_ServiceDesc, srv)
}

func _PingPongService_SendPing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ping)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingPongServiceServer).SendPing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pingpong.PingPongService/SendPing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingPongServiceServer).SendPing(ctx, req.(*Ping))
	}
	return interceptor(ctx, in, info, handler)
}

func _PingPongService_StreamPingPong_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PingPongServiceServer).StreamPingPong(&pingPongServiceStreamPingPongServer{stream})
}

type PingPongService_StreamPingPongServer interface {
	Send(*Pong) error
	Recv() (*Ping, error)
	grpc.ServerStream
}

type pingPongServiceStreamPingPongServer struct {
	grpc.ServerStream
}

func (x *pingPongServiceStreamPingPongServer) Send(m *Pong) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pingPongServiceStreamPingPongServer) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PingPongService_ReceivePongStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingPongServiceServer).ReceivePongStream(m, &pingPongServiceReceivePongStreamServer{stream})
}

type PingPongService_ReceivePongStreamServer interface {
	Send(*Pong) error
	grpc.ServerStream
}

type pingPongServiceReceivePongStreamServer struct {
	grpc.ServerStream
}

func (x *pingPongServiceReceivePongStreamServer) Send(m *Pong) error {
	return x.ServerStream.SendMsg(m)
}

func _PingPongService_PingAndStreamPong_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Ping)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingPongServiceServer).PingAndStreamPong(m, &pingPongServicePingAndStreamPongServer{stream})
}

type PingPongService_PingAndStreamPongServer interface {
	Send(*Pong) error
	grpc.ServerStream
}

type pingPongServicePingAndStreamPongServer struct {
	grpc.ServerStream
}

func (x *pingPongServicePingAndStreamPongServer) Send(m *Pong) error {
	return x.ServerStream.SendMsg(m)
}

// PingPongService_ServiceDesc is the grpc.ServiceDesc for PingPongService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingPongService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pingpong.PingPongService",
	HandlerType: (*PingPongServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPing",
			Handler:    _PingPongService_SendPing_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPingPong",
			Handler:       _PingPongService_StreamPingPong_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ReceivePongStream",
			Handler:       _PingPongService_ReceivePongStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PingAndStreamPong",
			Handler:       _PingPongService_PingAndStreamPong_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pingpong.proto",
}
